-- Server-only production archive schema. No browser/client policies are created.

create table if not exists public.spice_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  created_at timestamptz not null default now(),
  kind text not null,
  external_id text,
  payload jsonb not null default '{}'::jsonb
);

create unique index if not exists spice_events_external_id_uq
  on public.spice_events(external_id) where external_id is not null;

alter table public.spice_events enable row level security;

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  persona_id text not null,
  candidate_id text,
  media_job_id text,
  object_path text not null unique,
  mime_type text,
  sha256 text,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.media_assets enable row level security;

insert into storage.buckets (id, name, public)
values ('spice-private', 'spice-private', false)
on conflict (id) do update set public = false;

revoke all on public.spice_events from anon, authenticated;
revoke all on public.media_assets from anon, authenticated;
